name: myspace 93 leaderboard

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: XXX Notification
      run: |
        python main.py


    - name: List files
      run: |
        ls -R

    - name: Commit and Push
      run: |
        git branch
        git checkout gh-pages
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git status
        git add index.md
        git status
        git commit -m "Commit new leaderboard"
        git push
